# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddd629ebb92c6044146259cd3b99910d367f60c4d5db7151cd397d353ec9437fb9670d8983df51d3cd904f29726bce0d0c87273f7f99c88d60ad6d04c56222c9

test:
  secret_key_base: 3f70941d0fec8e886671970350ec418f4c19c878495397cf15788a0bb47025c4a7a34b8fd48723561f5e0adf7917bd2a772f79a1c53444379ae77900f51e89ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
